name       : libdc1394
version    : 2.2.6
release    : 2
source     :
    - https://netcologne.dl.sourceforge.net/project/libdc1394/libdc1394-2/2.2.6/libdc1394-2.2.6.tar.gz : 2b905fc9aa4eec6bdcf6a2ae5f5ba021232739f5be047dec8fe8dd6049c10fed
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Capture and control API for IIDC compliant cameras
description: |
    Capture and control API for IIDC compliant cameras
builddeps  :
    - pkgconfig(libraw1394)
    - pkgconfig(libusb-1.0)
libsplit   : no
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
